---
- name: httpd install
  yum:
    name: httpd
    state: latest

- name: httpd start
  service:
    name: httpd
    state: started
    enabled: true

- name: ".htaccessを有効にする"
  replace: 
    path: /etc/httpd/conf/httpd.conf
    regexp: 'AllowOverride None'
    replace: 'AllowOverride All'

- name: copy apache conf
  template:
    src: "vhosts.conf.j2"
    dest: "/etc/httpd/conf.d/vhosts.conf"
    owner: root
    group: root
    mode: 0644

- name: "Apache再起動"
  service:
    name: httpd
    state: restarted
