---
- name: install php repository
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present

- name: install php 7.2
  yum:
    name: "{{ packages }}"
    enablerepo: remi-php72
    state: latest
  vars:
    packages:
      - php
      - php-devel
      - php-common
      - php-fpm
      - php-opcache
      - php-pecl-redis
      - php-mbstring
      - php-mcrypt
      - php-mysqlnd
      - php-pdo
      - php-gd
      - php-xml
      - php-zip

- name: setting php timezone
  replace:
    path: /etc/php.ini
    regexp: '^;date.timezone ='
    replace: 'date.timezone = Asia/Tokyo'

- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/bin && mv /bin/composer.phar /bin/composer
  args:
    creates: /bin/composer
