- name: setup server
  hosts: all
  become: yes
  tasks:
    # SELinux停止
    - name: "SELinuxのDisable設定"
      selinux: state=disabled

    # ロケールの設定
    - name: "add ja_JP.UTF-8 to locale"
      shell: localedef -f UTF-8 -i ja_JP /usr/lib/locale/ja_JP.UTF-8

    - name: "set locale"
      shell: localectl set-locale LANG=ja_JP.utf8
      when: ansible_env.LANG | default('') != 'ja_JP.UTF-8'

    - name: "set timezone to Asia/Tokyo"
      timezone:
        name: Asia/Tokyo

- name: setup web applications
  hosts: all
  become: yes
  roles:
    - php
    - mysql
    - httpd
